In [19]:
import numpy as np
import pandas as pd

In [20]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [21]:
df = pd.read_csv('covid_toy.csv')

In [22]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [23]:
df.sample(5)

    age  gender  fever   cough       city has_covid
14   51    Male  104.0    Mild  Bangalore        No
6    14    Male  101.0  Strong  Bangalore        No
81   65    Male   99.0    Mild      Delhi        No
22   71  Female   98.0  Strong    Kolkata       Yes
51   11  Female  100.0  Strong    Kolkata       Yes

In [28]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [29]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [30]:
X_train

    age  gender  fever   cough       city
59    6  Female  104.0    Mild    Kolkata
30   15    Male  101.0    Mild      Delhi
27   33  Female  102.0  Strong      Delhi
90   59  Female   99.0  Strong      Delhi
98    5  Female   98.0  Strong     Mumbai
..  ...     ...    ...     ...        ...
85   16  Female  103.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata

[80 rows x 5 columns]

1. Aam Zindagi

In [34]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [38]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [40]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [41]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [43]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

Mentos Zindagi

In [44]:
from sklearn.compose import ColumnTransformer

In [45]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [46]:
transformer.fit_transform(X_train).shape

(80, 7)

In [47]:
transformer.transform(X_test).shape

(20, 7)